name: 2. CI/CD Pipeline (автоматически при merge)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Получить код репозитория
        uses: actions/checkout@v4

      - name: Установить Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Установить зависимости
        run: npm ci

      - name: Запустить тесты
        run: npm test
