name: 3. 🚀 Деплой в продакшн (ручной запуск)

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: |
          Версия релиза для деплоя в формате semver (например: 1.0.0, 2.1.0)

          📍 Где найти:
          • Actions → "3. Создание релиза" → версия после v
          • Issues → "Релиз v1.0.0" → версия после v
          • Code → Tags → последний тег (v1.0.0)
          • Releases → версия релиза

          ⚠️ Деплоить можно только успешно созданные релизы!
          ⚠️ Указывайте версию БЕЗ префикса 'v' (например: 1.0.0, а не v1.0.0)

          Пример: 1.0.0
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Валидация версии
      run: |
        VERSION="${{ github.event.inputs.release_version }}"
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Неверный формат версии: $VERSION"
          echo "Используйте формат: 1.0.0, 2.1.0, etc. (БЕЗ префикса 'v')"
          exit 1
        fi
        echo "✅ Версия $VERSION валидна"

    - name: Получить код репозитория
      uses: actions/checkout@v4

    - name: Авторизация в Yandex Container Registry
      uses: docker/login-action@v3
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Проверить существование Docker образа
      run: |
        IMAGE_NAME="cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}-latest"
        echo "Проверка существования образа: $IMAGE_NAME"

        if docker manifest inspect $IMAGE_NAME > /dev/null 2>&1; then
          echo "✅ Docker образ найден: $IMAGE_NAME"
          echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "❌ Docker образ не найден: $IMAGE_NAME"
          echo "Возможные причины:"
          echo "1. Релиз v${{ github.event.inputs.release_version }} не был создан"
          echo "2. Хотфикс не был применен (если деплоите после хотфикса)"
          echo "3. Неправильный формат версии"
          echo ""
          echo "Доступные образы для версии ${{ github.event.inputs.release_version }}:"
          docker images --filter "reference=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}*" --format "table {{.Repository}}:{{.Tag}}\t{{.CreatedAt}}" || echo "Нет доступных образов"
          echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
          exit 1
        fi

    - name: Настроить SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VM_SSH_KEY }}

    - name: Деплой на продакшн VM
      run: |
        IMAGE_NAME="cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}-latest"
        VERSION="${{ github.event.inputs.release_version }}"

        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << EOF
          echo "🚀 Начинаем деплой версии v$VERSION"
          echo "Образ: $IMAGE_NAME"

          # Авторизация в Yandex Container Registry
          echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' | docker login --username json_key --password-stdin cr.yandex

          # Остановить и удалить старый контейнер
          docker stop shri-app || true
          docker rm shri-app || true

          # Загрузить новый образ
          echo "Загружаем образ: $IMAGE_NAME"
          docker pull $IMAGE_NAME

          # Запустить новый контейнер
          echo "Запускаем новый контейнер..."
          docker run -d \
            --name shri-app \
            --restart unless-stopped \
            -p 80:3000 \
            -e NODE_ENV=production \
            -e APP_VERSION=v$VERSION \
            $IMAGE_NAME

          # Проверить статус
          sleep 5
          if docker ps | grep -q shri-app; then
            echo "✅ Деплой успешно завершен"
            echo "Версия v$VERSION развернута"
            echo "DEPLOY_STATUS=success" >> deployment_status.txt
          else
            echo "❌ Деплой не удался"
            echo "DEPLOY_STATUS=failed" >> deployment_status.txt
            exit 1
          fi

          # Показать информацию о запущенном контейнере
          echo "Информация о контейнере:"
          docker ps --filter "name=shri-app" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
        EOF

    - name: Обновить статус деплоя в issues
      uses: actions/github-script@v7
      with:
        script: |
          const releaseVersion = '${{ github.event.inputs.release_version }}';

          // Найти issue связанный с релизом
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'release',
            state: 'open'
          });

          const releaseIssue = issues.find(issue =>
            issue.title.includes(`Релиз v${releaseVersion}`)
          );

          const deploymentComment = `## 🚀 Деплой в продакшн

          **Дата деплоя:** ${new Date().toLocaleString('ru-RU')}
          **Автор деплоя:** @${{ github.actor }}
          **Версия:** v${releaseVersion}

          ### Статус:
          ✅ Релиз успешно выкачен в продакшн

          ### Детали:
          - Docker образ: \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${releaseVersion}-latest\`
          - Хост: \`${{ secrets.VM_HOST }}\`
          - Контейнер: \`shri-app\`
          - Порт: \`80:3000\`
          - Переменные окружения: \`NODE_ENV=production\`, \`APP_VERSION=v${releaseVersion}\`

          🎉 **Деплой завершен успешно!**

          📱 **Приложение доступно по адресу:** http://${{ secrets.VM_HOST }}/hw/store
          `;

          if (releaseIssue) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: releaseIssue.number,
              body: deploymentComment
            });

            // Добавляем лейбл о том, что релиз задеплоен
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: releaseIssue.number,
              labels: ['deployed']
            });

            console.log('Обновлен issue #' + releaseIssue.number);
          } else {
            console.log('Не найден связанный issue для версии v' + releaseVersion);
          }

    - name: Создать deployment в GitHub
      uses: actions/github-script@v7
      with:
        script: |
          const releaseVersion = '${{ github.event.inputs.release_version }}';

          // Создаем deployment
          const { data: deployment } = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `v${releaseVersion}`,
            environment: 'production',
            description: `Деплой версии v${releaseVersion}`,
            auto_merge: false,
            required_contexts: []
          });

          // Обновляем статус deployment
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment.id,
            state: 'success',
            description: `Успешно задеплоено на ${process.env.VM_HOST}`,
            environment_url: `http://${{ secrets.VM_HOST }}/hw/store`
          });

          console.log('Создан deployment для версии v' + releaseVersion);
