name: 4. 🔧 Хотфикс → затем запустить "3. 🚀 Деплой" (ручной запуск)

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: |
          Версия релиза для хотфикса в формате semver (например: 1.0.0, 2.1.0)

          📍 Где найти:
          • Actions → "2. Создание релиза" → версия после v
          • Issues → "Релиз v1.0.0" → версия после v
          • Code → Tags → последний тег (v1.0.0)
          • Releases → версия релиза

          ⚠️ Хотфикс можно делать только для успешно созданных релизов!
          ⚠️ Указывайте версию БЕЗ префикса 'v' (например: 1.0.0, а не v1.0.0)

          Пример: 1.0.0
        required: true
        type: string
      hotfix_description:
        description: 'Описание исправлений в хотфиксе (какие баги исправлены)'
        required: false
        type: string
        default: 'Критические исправления'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Валидация версии
      run: |
        VERSION="${{ github.event.inputs.release_version }}"
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Неверный формат версии: $VERSION"
          echo "Используйте формат: 1.0.0, 2.1.0, etc. (БЕЗ префикса 'v')"
          exit 1
        fi
        echo "✅ Версия $VERSION валидна"

    - name: Получить ветку релиза
      uses: actions/checkout@v4
      with:
        ref: releases/v${{ github.event.inputs.release_version }}

    - name: Настроить Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Установить зависимости
      run: npm ci

    - name: Запустить линтер
      run: npm run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Валидация версии
      run: |
        VERSION="${{ github.event.inputs.release_version }}"
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Неверный формат версии: $VERSION"
          echo "Используйте формат: 1.0.0, 2.1.0, etc. (БЕЗ префикса 'v')"
          exit 1
        fi
        echo "✅ Версия $VERSION валидна"

    - name: Получить ветку релиза
      uses: actions/checkout@v4
      with:
        ref: releases/v${{ github.event.inputs.release_version }}

    - name: Настроить Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Установить зависимости
      run: npm ci

    - name: Проверить типы
      run: npx tsc --noEmit

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Валидация версии
      run: |
        VERSION="${{ github.event.inputs.release_version }}"
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Неверный формат версии: $VERSION"
          echo "Используйте формат: 1.0.0, 2.1.0, etc. (БЕЗ префикса 'v')"
          exit 1
        fi
        echo "✅ Версия $VERSION валидна"

    - name: Получить ветку релиза
      uses: actions/checkout@v4
      with:
        ref: releases/v${{ github.event.inputs.release_version }}

    - name: Настроить Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Установить зависимости
      run: npm ci

    - name: Запустить тесты
      run: npm test

  hotfix:
    needs: [lint, typecheck, test]
    runs-on: ubuntu-latest

    steps:
    - name: Валидация версии
      run: |
        VERSION="${{ github.event.inputs.release_version }}"
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Неверный формат версии: $VERSION"
          echo "Используйте формат: 1.0.0, 2.1.0, etc. (БЕЗ префикса 'v')"
          exit 1
        fi
        echo "✅ Версия $VERSION валидна"

    - name: Получить ветку релиза
      uses: actions/checkout@v4
      with:
        ref: releases/v${{ github.event.inputs.release_version }}
        fetch-depth: 0

    - name: Вычислить версию хотфикса
      id: hotfix_version
      run: |
        BASE_VERSION="${{ github.event.inputs.release_version }}"

        # Получаем последний номер хотфикса для данной версии
        LAST_HOTFIX=$(git tag -l "v${BASE_VERSION}-hotfix.*" | sed "s/v${BASE_VERSION}-hotfix\.//" | sort -n | tail -1)

        if [ -z "$LAST_HOTFIX" ]; then
          HOTFIX_NUMBER=1
        else
          HOTFIX_NUMBER=$((LAST_HOTFIX + 1))
        fi

        HOTFIX_VERSION="${BASE_VERSION}-hotfix.${HOTFIX_NUMBER}"
        echo "hotfix_version=$HOTFIX_VERSION" >> $GITHUB_OUTPUT
        echo "hotfix_number=$HOTFIX_NUMBER" >> $GITHUB_OUTPUT
        echo "Версия хотфикса: v$HOTFIX_VERSION"

    - name: Настроить Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Установить зависимости
      run: npm ci

    - name: Обновить версию в package.json
      run: |
        HOTFIX_VERSION="${{ steps.hotfix_version.outputs.hotfix_version }}"
        npm version $HOTFIX_VERSION --no-git-tag-version
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json package-lock.json
        git commit -m "chore: bump version to $HOTFIX_VERSION (hotfix)"

    - name: Собрать проект
      run: npm run build

    - name: Авторизация в Yandex Container Registry
      uses: docker/login-action@v3
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Настроить Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Собрать и загрузить Docker образ хотфикса
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ steps.hotfix_version.outputs.hotfix_version }}
          cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}-latest
        platforms: linux/amd64

    - name: Создать Git тег
      run: |
        HOTFIX_VERSION="${{ steps.hotfix_version.outputs.hotfix_version }}"
        git tag v$HOTFIX_VERSION
        git push origin v$HOTFIX_VERSION

    - name: Получить предыдущий тег релиза/фикса
      id: prev_tag
      run: |
        BASE_VERSION="${{ github.event.inputs.release_version }}"

        # Получаем все теги для данной версии (включая хотфиксы) и сортируем их
        PREV_TAG=$(git tag -l "v${BASE_VERSION}*" | grep -E "^v${BASE_VERSION}(-hotfix\.[0-9]+)?$" | sort -V | tail -2 | head -1)

        if [ -z "$PREV_TAG" ]; then
          PREV_TAG="v${BASE_VERSION}"
        fi

        echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
        echo "Предыдущий тег: $PREV_TAG"

    - name: Получить коммиты с последнего релиза/фикса
      id: commits
      run: |
        COMMITS=$(git log --oneline ${{ steps.prev_tag.outputs.prev_tag }}..HEAD --pretty=format:"- %s (%h)")
        echo "commits<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMITS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Обновить связанные issues
      uses: actions/github-script@v7
      with:
        script: |
          const baseVersion = '${{ github.event.inputs.release_version }}';
          const hotfixVersion = '${{ steps.hotfix_version.outputs.hotfix_version }}';
          const hotfixNumber = '${{ steps.hotfix_version.outputs.hotfix_number }}';
          const hotfixDescription = '${{ github.event.inputs.hotfix_description }}' || 'Критические исправления';

          // Найти issue связанный с релизом
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'release',
            state: 'open'
          });

          const releaseIssue = issues.find(issue =>
            issue.title.includes(`Релиз v${baseVersion}`)
          );

          if (releaseIssue) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: releaseIssue.number,
              body: `## 🔧 Хотфикс v${hotfixVersion}

              **Дата фикса:** ${new Date().toLocaleString('ru-RU')}
              **Автор фикса:** @${{ github.actor }}
              **Номер хотфикса:** ${hotfixNumber}

              ### 🐛 Описание исправлений:
              ${hotfixDescription}

              ### 📋 Коммиты:
              ${{ steps.commits.outputs.commits }}

              ### 🐳 Docker образы:
              - \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${hotfixVersion}\`
              - \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${baseVersion}-latest\`

              ### ✅ Статус:
              Хотфикс создан и готов к деплою

              **Следующий шаг:** Запустите "3. 🚀 Деплой в продакшн" с версией \`${baseVersion}\`
              `
            });

            // Добавляем лейбл хотфикса
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: releaseIssue.number,
              labels: [`hotfix:${hotfixVersion}`]
            });

            console.log('Обновлен issue #' + releaseIssue.number);
          } else {
            console.log('Не найден связанный issue для версии v' + baseVersion);
          }

    - name: Создать GitHub Release для хотфикса
      uses: actions/github-script@v7
      with:
        script: |
          const baseVersion = '${{ github.event.inputs.release_version }}';
          const hotfixVersion = '${{ steps.hotfix_version.outputs.hotfix_version }}';
          const hotfixDescription = '${{ github.event.inputs.hotfix_description }}' || 'Критические исправления';

          await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${hotfixVersion}`,
            name: `Hotfix v${hotfixVersion}`,
            body: `## Хотфикс v${hotfixVersion}

            Исправления для релиза v${baseVersion}

            ### 🐛 Описание исправлений:
            ${hotfixDescription}

            ### 📋 Коммиты:
            ${{ steps.commits.outputs.commits }}

            ### 🐳 Docker образы:
            - \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${hotfixVersion}\`
            - \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${baseVersion}-latest\`
            `,
            draft: false,
            prerelease: false
          });

          console.log('Создан GitHub Release v' + hotfixVersion);
